################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk/platform/emlib/src/em_burtc.c \
C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk/platform/emlib/src/em_cmu.c \
C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk/platform/emlib/src/em_core.c \
C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk/platform/emlib/src/em_emu.c \
C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk/platform/emlib/src/em_eusart.c \
C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk/platform/emlib/src/em_gpio.c \
C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk/platform/emlib/src/em_i2c.c \
C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk/platform/emlib/src/em_iadc.c \
C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk/platform/emlib/src/em_ldma.c \
C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk/platform/emlib/src/em_msc.c \
C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk/platform/emlib/src/em_system.c \
C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk/platform/emlib/src/em_timer.c \
C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk/platform/emlib/src/em_usart.c 

OBJS += \
./gecko_sdk_4.2.3/platform/emlib/src/em_burtc.o \
./gecko_sdk_4.2.3/platform/emlib/src/em_cmu.o \
./gecko_sdk_4.2.3/platform/emlib/src/em_core.o \
./gecko_sdk_4.2.3/platform/emlib/src/em_emu.o \
./gecko_sdk_4.2.3/platform/emlib/src/em_eusart.o \
./gecko_sdk_4.2.3/platform/emlib/src/em_gpio.o \
./gecko_sdk_4.2.3/platform/emlib/src/em_i2c.o \
./gecko_sdk_4.2.3/platform/emlib/src/em_iadc.o \
./gecko_sdk_4.2.3/platform/emlib/src/em_ldma.o \
./gecko_sdk_4.2.3/platform/emlib/src/em_msc.o \
./gecko_sdk_4.2.3/platform/emlib/src/em_system.o \
./gecko_sdk_4.2.3/platform/emlib/src/em_timer.o \
./gecko_sdk_4.2.3/platform/emlib/src/em_usart.o 

C_DEPS += \
./gecko_sdk_4.2.3/platform/emlib/src/em_burtc.d \
./gecko_sdk_4.2.3/platform/emlib/src/em_cmu.d \
./gecko_sdk_4.2.3/platform/emlib/src/em_core.d \
./gecko_sdk_4.2.3/platform/emlib/src/em_emu.d \
./gecko_sdk_4.2.3/platform/emlib/src/em_eusart.d \
./gecko_sdk_4.2.3/platform/emlib/src/em_gpio.d \
./gecko_sdk_4.2.3/platform/emlib/src/em_i2c.d \
./gecko_sdk_4.2.3/platform/emlib/src/em_iadc.d \
./gecko_sdk_4.2.3/platform/emlib/src/em_ldma.d \
./gecko_sdk_4.2.3/platform/emlib/src/em_msc.d \
./gecko_sdk_4.2.3/platform/emlib/src/em_system.d \
./gecko_sdk_4.2.3/platform/emlib/src/em_timer.d \
./gecko_sdk_4.2.3/platform/emlib/src/em_usart.d 


# Each subdirectory must supply rules for building sources it contributes
gecko_sdk_4.2.3/platform/emlib/src/em_burtc.o: C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk/platform/emlib/src/em_burtc.c gecko_sdk_4.2.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG24B210F1536IM48=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD2703A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\gecko_sdk_4.2.3\hardware\driver\bmp280\inc" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\gecko_sdk_4.2.3\hardware\driver\bmp280\bosch\BMP280_driver" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\config" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\autogen" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//app/common/util/app_log" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/common/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/driver/bmp280/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/driver/bmp280/bosch/BMP280_driver" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/board/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/device_init/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emdrv/common/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/driver/i2cspm/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/iostream/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/peripheral/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/common/toolchain/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/system/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/sleeptimer/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.2.3/platform/emlib/src/em_burtc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.2.3/platform/emlib/src/em_cmu.o: C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk/platform/emlib/src/em_cmu.c gecko_sdk_4.2.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG24B210F1536IM48=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD2703A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\gecko_sdk_4.2.3\hardware\driver\bmp280\inc" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\gecko_sdk_4.2.3\hardware\driver\bmp280\bosch\BMP280_driver" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\config" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\autogen" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//app/common/util/app_log" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/common/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/driver/bmp280/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/driver/bmp280/bosch/BMP280_driver" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/board/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/device_init/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emdrv/common/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/driver/i2cspm/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/iostream/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/peripheral/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/common/toolchain/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/system/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/sleeptimer/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.2.3/platform/emlib/src/em_cmu.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.2.3/platform/emlib/src/em_core.o: C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk/platform/emlib/src/em_core.c gecko_sdk_4.2.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG24B210F1536IM48=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD2703A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\gecko_sdk_4.2.3\hardware\driver\bmp280\inc" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\gecko_sdk_4.2.3\hardware\driver\bmp280\bosch\BMP280_driver" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\config" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\autogen" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//app/common/util/app_log" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/common/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/driver/bmp280/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/driver/bmp280/bosch/BMP280_driver" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/board/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/device_init/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emdrv/common/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/driver/i2cspm/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/iostream/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/peripheral/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/common/toolchain/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/system/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/sleeptimer/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.2.3/platform/emlib/src/em_core.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.2.3/platform/emlib/src/em_emu.o: C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk/platform/emlib/src/em_emu.c gecko_sdk_4.2.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG24B210F1536IM48=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD2703A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\gecko_sdk_4.2.3\hardware\driver\bmp280\inc" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\gecko_sdk_4.2.3\hardware\driver\bmp280\bosch\BMP280_driver" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\config" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\autogen" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//app/common/util/app_log" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/common/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/driver/bmp280/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/driver/bmp280/bosch/BMP280_driver" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/board/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/device_init/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emdrv/common/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/driver/i2cspm/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/iostream/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/peripheral/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/common/toolchain/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/system/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/sleeptimer/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.2.3/platform/emlib/src/em_emu.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.2.3/platform/emlib/src/em_eusart.o: C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk/platform/emlib/src/em_eusart.c gecko_sdk_4.2.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG24B210F1536IM48=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD2703A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\gecko_sdk_4.2.3\hardware\driver\bmp280\inc" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\gecko_sdk_4.2.3\hardware\driver\bmp280\bosch\BMP280_driver" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\config" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\autogen" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//app/common/util/app_log" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/common/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/driver/bmp280/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/driver/bmp280/bosch/BMP280_driver" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/board/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/device_init/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emdrv/common/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/driver/i2cspm/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/iostream/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/peripheral/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/common/toolchain/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/system/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/sleeptimer/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.2.3/platform/emlib/src/em_eusart.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.2.3/platform/emlib/src/em_gpio.o: C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk/platform/emlib/src/em_gpio.c gecko_sdk_4.2.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG24B210F1536IM48=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD2703A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\gecko_sdk_4.2.3\hardware\driver\bmp280\inc" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\gecko_sdk_4.2.3\hardware\driver\bmp280\bosch\BMP280_driver" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\config" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\autogen" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//app/common/util/app_log" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/common/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/driver/bmp280/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/driver/bmp280/bosch/BMP280_driver" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/board/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/device_init/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emdrv/common/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/driver/i2cspm/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/iostream/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/peripheral/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/common/toolchain/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/system/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/sleeptimer/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.2.3/platform/emlib/src/em_gpio.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.2.3/platform/emlib/src/em_i2c.o: C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk/platform/emlib/src/em_i2c.c gecko_sdk_4.2.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG24B210F1536IM48=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD2703A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\gecko_sdk_4.2.3\hardware\driver\bmp280\inc" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\gecko_sdk_4.2.3\hardware\driver\bmp280\bosch\BMP280_driver" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\config" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\autogen" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//app/common/util/app_log" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/common/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/driver/bmp280/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/driver/bmp280/bosch/BMP280_driver" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/board/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/device_init/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emdrv/common/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/driver/i2cspm/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/iostream/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/peripheral/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/common/toolchain/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/system/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/sleeptimer/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.2.3/platform/emlib/src/em_i2c.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.2.3/platform/emlib/src/em_iadc.o: C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk/platform/emlib/src/em_iadc.c gecko_sdk_4.2.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG24B210F1536IM48=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD2703A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\gecko_sdk_4.2.3\hardware\driver\bmp280\inc" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\gecko_sdk_4.2.3\hardware\driver\bmp280\bosch\BMP280_driver" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\config" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\autogen" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//app/common/util/app_log" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/common/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/driver/bmp280/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/driver/bmp280/bosch/BMP280_driver" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/board/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/device_init/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emdrv/common/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/driver/i2cspm/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/iostream/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/peripheral/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/common/toolchain/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/system/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/sleeptimer/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.2.3/platform/emlib/src/em_iadc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.2.3/platform/emlib/src/em_ldma.o: C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk/platform/emlib/src/em_ldma.c gecko_sdk_4.2.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG24B210F1536IM48=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD2703A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\gecko_sdk_4.2.3\hardware\driver\bmp280\inc" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\gecko_sdk_4.2.3\hardware\driver\bmp280\bosch\BMP280_driver" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\config" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\autogen" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//app/common/util/app_log" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/common/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/driver/bmp280/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/driver/bmp280/bosch/BMP280_driver" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/board/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/device_init/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emdrv/common/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/driver/i2cspm/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/iostream/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/peripheral/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/common/toolchain/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/system/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/sleeptimer/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.2.3/platform/emlib/src/em_ldma.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.2.3/platform/emlib/src/em_msc.o: C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk/platform/emlib/src/em_msc.c gecko_sdk_4.2.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG24B210F1536IM48=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD2703A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\gecko_sdk_4.2.3\hardware\driver\bmp280\inc" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\gecko_sdk_4.2.3\hardware\driver\bmp280\bosch\BMP280_driver" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\config" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\autogen" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//app/common/util/app_log" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/common/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/driver/bmp280/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/driver/bmp280/bosch/BMP280_driver" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/board/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/device_init/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emdrv/common/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/driver/i2cspm/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/iostream/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/peripheral/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/common/toolchain/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/system/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/sleeptimer/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.2.3/platform/emlib/src/em_msc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.2.3/platform/emlib/src/em_system.o: C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk/platform/emlib/src/em_system.c gecko_sdk_4.2.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG24B210F1536IM48=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD2703A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\gecko_sdk_4.2.3\hardware\driver\bmp280\inc" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\gecko_sdk_4.2.3\hardware\driver\bmp280\bosch\BMP280_driver" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\config" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\autogen" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//app/common/util/app_log" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/common/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/driver/bmp280/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/driver/bmp280/bosch/BMP280_driver" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/board/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/device_init/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emdrv/common/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/driver/i2cspm/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/iostream/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/peripheral/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/common/toolchain/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/system/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/sleeptimer/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.2.3/platform/emlib/src/em_system.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.2.3/platform/emlib/src/em_timer.o: C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk/platform/emlib/src/em_timer.c gecko_sdk_4.2.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG24B210F1536IM48=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD2703A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\gecko_sdk_4.2.3\hardware\driver\bmp280\inc" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\gecko_sdk_4.2.3\hardware\driver\bmp280\bosch\BMP280_driver" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\config" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\autogen" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//app/common/util/app_log" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/common/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/driver/bmp280/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/driver/bmp280/bosch/BMP280_driver" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/board/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/device_init/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emdrv/common/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/driver/i2cspm/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/iostream/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/peripheral/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/common/toolchain/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/system/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/sleeptimer/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.2.3/platform/emlib/src/em_timer.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.2.3/platform/emlib/src/em_usart.o: C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk/platform/emlib/src/em_usart.c gecko_sdk_4.2.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG24B210F1536IM48=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD2703A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\gecko_sdk_4.2.3\hardware\driver\bmp280\inc" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\gecko_sdk_4.2.3\hardware\driver\bmp280\bosch\BMP280_driver" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\config" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan\autogen" -I"C:\Users\admin\SimplicityStudio\v5_workspace\i2c_scan" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//app/common/util/app_log" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/common/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/driver/bmp280/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/driver/bmp280/bosch/BMP280_driver" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//hardware/board/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/device_init/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emdrv/common/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/driver/i2cspm/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/iostream/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/peripheral/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/common/toolchain/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/system/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/sleeptimer/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.2.3/platform/emlib/src/em_usart.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


